---
- name: add PPA repository for PHP 7.0
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: install PHP 7.0 component
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - php7.0-fpm
    - php7.0-cli
    - php7.0-common
    - php7.0-gd
    - php7.0-mysql
    - php7.0-mcrypt
    - php7.0-curl
    - php7.0-intl
    - php7.0-xsl
    - php7.0-mbstring
    - php7.0-zip
    - php7.0-bcmath
    - php7.0-iconv
    - php7.0-imap
    - php7.0-xmlrpc
    - php7.0-dev
    - php7.0-soap
